### ISSUE TITLE
linereader is not working

### ISSUE THREAD

**Issue by amitguptagwl** [jasmine/jasmine-npm#106]
Following snippet is not working to read a file line-by-line;

```
 var lineReader = require('readline').createInterface({
    input: require('fs').createReadStream('dbsets/employee.txt')
  });

lineReader.on('line', function (line) {
  console.log('Line from file:', line);
});
```

I have tried other npm modules to read file line by line. But none of them work from jasmine file. However they work fine directly.

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

At a glance, I would guess that it's related to the file reading in node.js being async. Closing this since it sounds like a how to question and not necessarily an issue with Jasmine itself. Thanks for using Jasmine!

**Comment by amitguptagwl** [comment]
yes, it seems an issue with async call reading. or may be I used some wrong way to assert it. Thanks for your response
