### ISSUE TITLE
Make tests run in "random" order by default

### ISSUE THREAD

**Issue by pmeinhardt** [jasmine/jasmine-npm#112]
Hey, first off: thanks for creating Jasmine!

When I initialize a new project by running `jasmine init`, it creates a standard `jasmine.json` config file. I was wondering why the `"random"` test execution order is not enabled by default?

To me at least, this would be a sensible default for new projects.

**Comment by slackersoft** [comment]
We didn't want to turn on randomization by default, since it could potentially break existing suites, that are order dependent (even if accidentally). Even though `jasmine init` is intended for a new codebase that most likely doesn't have any specs yet, I think we want to leave the default alone until we bump to 3.0 and we can have breaking changes.

Closing this. Thanks for using Jasmine!

**Comment by pmeinhardt** [comment]
Thanks for the quick reply 🤘 

I totally understand you don't want to change the tool's default behavior before making a new major version release. At the same time I wonder whether changing the default value in the config template for new projects is much of a breaking change (except if somehow you rely on newly generated config files to always look exactly the same?).

Should we at least keep this issue open to keep track of this proposal for an upcoming 3.0 release?

Thanks again and cheers 🙂
