### ISSUE TITLE
Reporter limitation: Mark suites/specs if focused 

### ISSUE THREAD

**Issue by onury** [jasmine/jasmine-npm#123]
When `fit` or `fdescribe` is used, Jasmine marks the rest of the specs as disabled (like they're under `xdescribe`). 

This way; when building a custom reporter, there is no way to know if a suite or spec is focused. This information would be very useful; for example, you could report and/or warn the user that the reported results are of "focused" specs only.

The state passed to custom reporter handlers (such as `suiteStarted`, `specStarted` and `jasmineStarted`) should include this information.

### on `jasmineStarted`
```js
{ 
    totalSpecsDefined: 16,
    totalSpecsFocused: 1,        // <——  so the reporter knows, there are focused specs
    order: { 
        random: false, 
        seed: '53935', 
        sort: [Function: naturalOrder] 
    } 
}
```
When `totalSpecsFocused` is provided here, the reporter knows right at the beginning; that we're not running a full suite test. This is a very crucial information to be reported to the user. 

### on `suiteStarted`
```js
{ 
    id: 'suite1',
    description: 'Suite 1:',
    fullName: 'Suite 1:',
    failedExpectations: [],
    focused: true               // <——  suite with fdescribe is marked
}
```

### on `specStarted`
```js
{ 
    id: 'spec2',
    description: 'should mark focused',
    fullName: 'Suite 1: should mark focused',
    failedExpectations: [],
    passedExpectations: [],
    pendingReason: '',
    focused: true               // <——  spec with fit is marked
}
```

**Comment by slackersoft** [comment]
This jives with something we've been throwing around for a little while. We have a [tracker story](https://www.pivotaltracker.com/story/show/78679648) that would require focused status of some sort to be passed out to reporters. At this point, I don't think this is going to make it until 3.0, since we're going to need to rejigger the status' that we use for `xit`, `fit`, and `pending` as well as their `describe` counterparts, because they aren't consistent now. Additionally, this functionality really needs to be in [jasmine-core](https://github.com/jasmine/jasmine) and not just the npm packaging.

Hope this helps. Thanks for using Jasmine!

**Comment by onury** [comment]
Thanks for building it ;)

I agree on the status semantics. 
Should I open an additional issue @ jasmine-core?

**Comment by slackersoft** [comment]
We can leave it either way. I would like to only have a single open issue for a given feature, so if you want to open an issue on jasmine-core, we should close this one.

**Comment by onury** [comment]
ok, leaving as is. thanks

**Comment by slackersoft** [comment]
Spec status was pretty heavily reworked in Jasmine 3.0 to make some of this a bit more clear for reporters.

`xdescribe`, `xit`, `pending()`, and specs with no callback will all report as `pending`.

Using an `fit` or `fdescribe` or otherwise filtering which specs are run will cause any other specs that exist to report as `excluded`. There is also a new attribute in the `jasmineDone` [details](https://jasmine.github.io/api/edge/global.html#JasmineDoneInfo) for overall status which will report as `incomplete` if specs were excluded from the run.

Hope this helps. Thanks for using Jasmine!

**Comment by slackersoft** [comment]
I'm going to close this issue, since I think the underlying use case is solved in Jasmine 3.0. Please let us know if there is still some additional status we missed.

Thanks for using Jasmine!

**Comment by onury** [comment]
I was actually working on [the reporter](https://github.com/onury/jasmine-console-reporter) and there is still no way to detect you're running focused specs until you hit a spec with `excluded` state. 

I still think the param passed to `jasmineStarted` should have either a `totalSpecsFocused` or `totalSpecsExcluded` property, so that the reporter knows beforehand.

**Comment by slackersoft** [comment]
I think the `overallStatus` [API docs](https://jasmine.github.io/api/edge/global.html#JasmineDoneInfo) should mostly solve your usecase. In Jasmine 3.0, it now has a third state that indicates that not all of the specs were executed. We think that `jasmineDone` is the appropriate place for this information, since that is the point at which we can inform reporters about failure state as well as simply whether or not anything has been focused.

Hope this helps. Thanks for using Jasmine!
