### ISSUE TITLE
Exclude directories?

### ISSUE THREAD

**Issue by amandapouget** [jasmine/jasmine-npm#128]
Is there any way to exclude directories in the configuration?

E.g. spec_files: <everything that ends in Spec.js EXCEPT things in the node_modules folder>

Sorry I can't find this anywhere else!

Thank you!

**Comment by slackersoft** [comment]
I'm not totally sure what you're looking to exclude here. Do you want to not supply the `spec_files` key in your jasmine.json? Or do you want to add a large glob and then another rule to remove things from that glob?

**Comment by mandysimon88** [comment]
I want to be able to say, “Run all the files in my entire repo ending with Spec.js EXCEPT files in node_modules”. There is not a way to express this because the current options allow for white-listing but not black-listing. Every time I add a new folder in my root directory, I have to add it to the white-listing.

Ironically, I could just let it run the few Spec.js files in node_modules, too (who cares?) except the ones that come built with Jasmine actually fail…

**Comment by slackersoft** [comment]
Ok, that makes sense. We would be happy to review a pull request that changes the behavior of the file loading code to allow a glob starting with `!` to cause previously included files to be excluded. So config that includes:

```json
```

**Comment by slackersoft** [comment]
@cancerberoSgx The `--filter` command line argument isn't meant for filtering files, but to limit which specs found in all of your spec files will be executed by Jasmine. This is why it doesn't accept globs. The Jasmine-npm package currently accepts files as the last argument on the command line, and this should work with globs just fine.

Hope this helps. Thanks for using Jasmine!

**Comment by cancerberoSgx** [comment]
OK now I got it , by looking at the code... I just created this one https://github.com/jasmine/jasmine-npm/pull/131 to add a small comment about filtering because at least for me was not clear and hard to find this info that IMO is important. Thanks and keep the good work!

**Comment by slackersoft** [comment]
#131 is merged. We would still be happy to review a pull request to allow `!` style globs in the `spec_files` option as mentioned previously.

**Comment by cancerberoSgx** [comment]
Iin general what I've seen for supporting this, is having two properties, "include" and "exclude". Current "spec_files" would be "include" and any file that matches any of the globs will be included. Then if any of the "exclude" glob matches the file it won't be included, not matter if it matches the "include" one. I've seen this in typescript tsconfig.json, vscode settings and others

If you don't want to define another property in jasmine.json, then the only way I see is doing kind of "Magic" and treat specially those globs that starts with "!". Won't be an OR anymore... Personally I don't like that - I would introduce another property like "spec_files_exclude". 

My two cents

**Comment by liuxh0** [comment]
What is current state of this issue? Would like to help if still not done.

In my opinion the `!` variant is okay since it doesn't introduce another property. But:

- I don't think it is a good idea to let order decide priority due to complexity. If you want to include something in a folder but eliminate the rest of the folder, I would do something like `folder/**/*.spec.ts`, instead of first eliminating the whole folder and then including files wanted.

**Comment by slackersoft** [comment]
To my knowledge no work has been started for this issue. I still don't have a strong preference on which mechanism is used to allow exclusion of files/folders, so if you want to take a look at this, you're welcome to use either approach.
