### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by elentok** [jasmine/jasmine-npm#14]
Is there a way to use this with coffeescript files?

**Comment by amavisca** [comment]
@elentok 
There's nothing built into this library to handle coffeescript files, but -

As long as you can pull in:
```
require('coffee-script/register');
```
before jasmine runs, it should work fine.

One way to do this is having your first spec helper (specified in your jasmine.json) simply do that require. This way when jasmine requires your other helpers, spec files, and source files, it is already able to handle coffeescript files.

I tested making a simple SpecHelper.js file that just does that require and was able to run .coffee specs + .coffee source + .coffee helpers.

Let me know if this solves your issue or if you think there's an easier way to solve this.

**Comment by euskode** [comment]
I have a --bare file watcher just for my spec directory where all CoffeeScript Jasmine tests reside.

This seems to work well, as jasmine only ever knows of the compiled Javascript files, but I do think that you can get this to work as described by @amavisca too.

**Comment by slackersoft** [comment]
With the changes we've made on master to ensure that helpers are always loaded. You should be able to create a helper file that loads first, that does the `require('coffee-script/register');` in order to get CoffeeScript support for your remaining helpers, specs, and code.

This seems like a reasonable solution to me, and one that allows any other type of transpiling that works the same way without jasmine-npm having to worry about each individual type of file. I'm going to close this issue, but feel free to open a new one if this doesn't work for you.

Thanks for using jasmine!
