### ISSUE TITLE
Specs are loaded more than once

### ISSUE THREAD

**Issue by UziTech** [jasmine/jasmine-npm#161]
When specs are loaded before jasmine is executed they will be loaded twice because the required file is removed from the cache.

https://github.com/jasmine/jasmine-npm/blob/e1657e3d6a45b74ed1a5dd16bfc2090ece7a82a3/lib/jasmine.js#L87-L92

**Comment by zarko-tg** [comment]
Probably related to what broke things for webdriverio once they bumped the dependency to 3.6.0: https://github.com/webdriverio/webdriverio/issues/5657

**Comment by slackersoft** [comment]
Looking back at the original PR for parallel specs (#153), it looks like the require cache for spec files was added in an effort to get some consistency and not because it fixed things like it did for helpers. Jasmine 3.6.1 has just been released with the cache busting removed. I'd appreciate if you could try it out and see if it's working better for you now.

Thanks for reporting this.
