### ISSUE TITLE
Breaking changes introduced as patch changes

### ISSUE THREAD

**Issue by fastman** [jasmine/jasmine-npm#174]
Hi,
`3.6.1` didn't have engines in `package.json` specifying which versions of Node.js are supported.
`3.6.2` version breaks compatibility with previously working versions of Node.js. 
`3.6.3` version specifies which versions of Node.js are support but up to `3.6.1` multiple versions, apart from the one listed in `pacakge.json` were supported. 
Shouldn't this be a breaking change?

**Comment by sgravrock** [comment]
I've removed the `engines` specification because, as you note, it was a breaking change for some users. For the rest, please see my comment in #166.

See <https://jasmine.github.io/setup/nodejs.html> for the list of supported Node versions. Note that odd-numbered versions are not supported. They're very likely to work at least until the next major release of Jasmine, but we can't offer compatibility guarantees for releases that have such a short lifespan.

**Comment by fastman** [comment]
@sgravrock Thanks for taking a loot at this! 
Engines was not the biggest issue - the the thing that broke the backwards compatibility (as noted - `3.6.2.`) was the introduction of async/await -> https://github.com/jasmine/jasmine-npm/commit/c8ebcffcf15388f4f530b1b5a805aa4e29074c89
