### ISSUE TITLE
Impossible to rerun in the same runtime because of require cache

### ISSUE THREAD

**Issue by soswow** [jasmine/jasmine-npm#30]
Hello,
This is really related to #5 
We are integrating this lib as a grunt task at the moment. Everything works great except for one thing.
We try to rerun specs every time something changes in the same runtime env. (so, in terms of grunt watch task it's ```options: {spawn: false}``` which mean there is no new node process. We need this to keep in our case webdriver client.
The problem is when we try to create and run jasmine-npm second time. Internally it uses `require(spec)` to load and register all the `describe`, `it` etc. Second time it doesn't do this, because `require` will use internal cache and never execute `describe` second time, hence won't register it and jasmine will report 0 specs found.
Our current solution is pretty hacky:
```javascript
    /**
     * Invalidate require internal cache for modules that contains provided
     * path part in it's full name.
     * @param path
     */
    var invalidateRequireCacheByPath = function (path) {
        for (var name in require.cache) {
            if (name.indexOf(path) >= 0) {
                delete require.cache[name];
            }
        }
    };

//..... 

            // jasmine-npm uses require() to load specs, during which time
            // all the "describe" "it" etc. register them self.
            // If we try to create second instance of jasmine-npm in the same runtime,
            // cached version of specs is taken and
            // 1) New test code is not loaded and not executed
            // 2) "describe" and other method are not called, hence specs are not registered
            invalidateRequireCacheByPath(options.spec_dir); 

```

So I was hoping we can think on better solution.

**Comment by amavisca** [comment]
I don't mind the idea of invalidating the cache. I think the alternative is to manually run code in a vm context. It's nice being able to offload the effort of execution to require.

If you'd like you could submit your cache invalidation + specs for it as a PR - otherwise I can add a fix to this.

**Comment by amavisca** [comment]
A problem with invalidating the cache is that this will only really the problem with your spec files. If your source files change and are being `require`'d  into your spec, you won't see a change in your source file within the same process because that file is still cached.

What wasn't working for you with spawning a new process?

**Comment by soswow** [comment]
I was using it with web driver. And i keep webdriver client reference to
speedup execution time.

**Comment by slackersoft** [comment]
I think if we get to a point where jasmine-npm has some ability to watch the project and run specs when files change, we will still need to spawn a child process to actually run the specs, given all of the issues around `require` caching.

Other workarounds would involve loading all of the code up into a vm that had a fresh cache each time, but that would probably still break your use case.

I've made some notes in #5 about making sure that new code is loaded and probably `fork`ing a child process to get a fresh cache. I'm going to close this in favor of that issue, since it seems like this has mostly morphed into that issue.

Thanks for using jasmine!
