### ISSUE TITLE
Display (or not) disabled specs?

### ISSUE THREAD

**Issue by LJWall** [jasmine/jasmine-npm#45]
Hi, 

I thought I'd found a bug that you don't get any output for specs which are contained in an `xdescribe` block, unlike the pending info printed for `xit`.  But then looking at `console_reporter_spec.js` it looks like it's deliberate?  This seems kind of dangerous..

Perhaps I'm misunderstanding something, but I've modified a fork (https://github.com/LJWall/jasmine-npm/tree/master) to report disabled specs with a yellow dash, and summarise disabled specs/suites at the end,

LJ

**Comment by slackersoft** [comment]
Specs marked as `disabled` probably shouldn't be reported, because a spec can also be reported as `disabled` if other specs have been focused with `fdescribe` or `fit`. If the suite has focused specs being run, non-focused specs should not be displayed by the reporter, because that could be confusing as to which specs were run.

Let's take the discussion of whether `xdescribe` should put child specs into `pending` or `disabled` over to the jasmine-core issue you created (jasmine/jasmine#855)

**Comment by amavisca** [comment]
It looks like disabled specs still get added to the spec count and displayed in the summary (but don't get a dot), so if you have one spec focused you get something like:
```
○ → jasmine
Started
.


5 specs, 0 failures
```

**Comment by LJWall** [comment]
Yes, it's a bit peculiar. Perhaps it could be more like the ruby gem reporter, so you'd get

```
Started
.

Ran 1 of 5 specs.
1 spec, 0 failures. 
```

As slackersoft says, no detailed reporting of which specs/suits are disabled, but perhaps a grey dot for disabled specs...

I can make a PR later...

**Comment by slackersoft** [comment]
I don't think we should display individual disabled specs, but the run counts from your pull request seem like a good compromise.

I'm going to close this issue, as that seems like a good resolution to me.
