### ISSUE TITLE
Unknown options are silently accepted.

### ISSUE THREAD

**Issue by cben** [jasmine/jasmine-npm#53]
It seems the jasmine command silently ignores any incorrect option.
A concrete example that wasted me hours: I was passing `--stop-on-failure` which had no effect; turns out I must pass `--stop-on-failure=true`.
Even `--help` is ignored and the tests just run!  (`jasmine help` works but I only discovered that by peeking at the source, which kinda misses the point of having a help option...)

I think the standard behavior of exiting with error message would be better for users.

**Comment by amavisca** [comment]
Oops, looks like the docs on --stop-on-failure are inaccurate. The docs repo lives at https://github.com/jasmine/jasmine.github.io if you want to send up a PR for that - otherwise I'll take care of that when I get a chance.

I think some sort of "unknown option" messaging would be a good idea when we find an unknown argument that starts with `--` or `-`.

**Comment by slackersoft** [comment]
We would be happy to review a pull request that causes the usage to be shown when an unknown argument is passed.
