### ISSUE TITLE
why not see result in terminal

### ISSUE THREAD

**Issue by lindazhang102** [jasmine/jasmine-npm#73]
why can't see the running result??help
<img width="291" alt="2016-02-23 9 34 17" src="https://cloud.githubusercontent.com/assets/7489661/13253459/23252392-da77-11e5-94d8-96ce5ac70975.png">

**Comment by slackersoft** [comment]
The default reporter for Jasmine only prints detailed information about specs that fail. Since you spec is passing, you only see the `.` printed. There is a project maintained by the community (jasmine-reporters) that has many other reporters. 

Next time you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using Jasmine! Closing.
