### ISSUE TITLE
Reliance `this` is bad practice (eg, fat arrow + helpers don't marry ).

### ISSUE THREAD

**Issue by Izhaki** [jasmine/jasmine-npm#97]
This is an issue that has many workarounds, but I still feel it is important to flag.

Using `this` as a way to pass context (shared object) seems like a rather fragile practice to me.

`this` has always been a can of warms in Javascript. To make matters better, the fat arrow syntax (`()=>`) was introduced to ES6. But this sometimes backfires, like in the case when you use helpers - whatever you put on `this` in helpers disappears once you get to a block that uses fat arrow.

![image](https://cloud.githubusercontent.com/assets/880132/19540534/1098756a-9658-11e6-8744-4dc8a73180cf.png)

A much more solid solution would be to simply pass a `context` argument to each `it` et al function. Alas, the `done` argument means such change will be a breaking change.

Anyhow, to solve this problem:

- Don't use fat arrows, simply use `function(){}`.
- Don't use helpers, simply require the helper function within the `beforeEach` of a block using fat arrow throughout.

Feel free to close this issue once read.

**Comment by amavisca** [comment]
Thanks for opening this - it's an interesting discussion I've felt pain around myself. 

I think the introduction of fat arrow has caused some developers to experience behavior they didn't expect.

At the same time it's frustrating because many developers (myself included) are often choosing to use fat arrow in place of a normal function declaration as a shorthand syntax....was that really the purpose of the fat arrow? The skinny arrow was explicitly rejected due to not providing a new syntax (simply a shorthand for function).

If you want to have further discussions about this (and discussions regarding a potential breaking interface), please open an issue in the jasmine/jasmine repo as this is just the node wrapper.
